feat(template): adjusts basic styling
starter-code/res-gen pull request #12
Opened 2020-10-17 23:59 UTC by PatrickDohn

Summary: 
  * adjust styling
  * updates example JSON with a summary field

2020-10-20 21:46 UTC, davidholyko approved these changes
LGTM

2020-10-20 21:46 UTC, davidholyko commented on src/components/routes/Routes.js
> +// import GoogleDocPage from '../pages/GoogleDocPage';
rm

2020-10-20 21:46 UTC, davidholyko commented on src/components/templates/GoogleDocTemplate/Heading.js
> +// import _ from 'lodash';
rm unused

2020-10-26 02:05 UTC, davidholyko requested changes
Needs to merge chore first

2020-10-27 22:48 UTC, PatrickDohn commented on src/components/pages/MahomesPage.js
> +    <div className="googleDoc-page">
Change class names as well. make sure its kabob case (mahomes-page)

2020-10-27 22:50 UTC, closed without merging