feat(home): home page styling idea
starter-code/res-gen pull request #35
Opened 2020-12-04 23:25 UTC by PatrickDohn

#### Summary

- Work Type: Feature 

#### What I did

- Set up the home page with styling idea
-
-

#### Checklist

- [ ] Branch is in format `TYPE/scope/description`
- [ ] PR title is in format `TYPE(scope): description`
- [ ] Commits are in semantic format
- [ ] Has Summary
- [ ] Has Labels

2020-12-06 03:53 UTC, davidholyko requested changes
Revert package-lock deletion

2020-12-06 03:59 UTC, davidholyko commented on src/scss/HomePage.scss
> +$base03: #002b36;
we probably want some kind of documentation for what these colors look like. Can we add that file into our documentation folder

2020-12-06 04:00 UTC, davidholyko commented on src/scss/HomePage.scss
> +  width: 100vw;
change width to 100%. 100vw looks different on windows.

2020-12-06 04:01 UTC, davidholyko commented on src/scss/HomePage.scss
> +  overflow: scroll;
change to overflow-y: overlay;

https://stackoverflow.com/questions/18548465/prevent-scroll-bar-from-adding-up-to-the-width-of-page-on-chrome

2020-12-06 04:03 UTC, davidholyko commented on src/components/pages/HomePage.js
> +      <div className="hero-section">
some of these divs are semantically <section></section> elements.

2020-12-06 04:03 UTC, davidholyko commented on src/components/pages/HomePage.js
> +        <div className="triple-content">
these content triplets are semantically article elements

2020-12-06 04:04 UTC, davidholyko commented on src/components/pages/HomePage.js
> +        <div className="footer-content">
footer element

2020-12-07 21:45 UTC, PatrickDohn commented on src/scss/HomePage.scss
> +  width: 100vw;
All fixed

2020-12-07 21:45 UTC, PatrickDohn commented on src/scss/HomePage.scss
> +  overflow: scroll;
Taken care of!

2020-12-07 23:34 UTC, PatrickDohn commented on src/scss/HomePage.scss
> +  overflow: scroll;
All set

2020-12-07 23:34 UTC, PatrickDohn commented on src/components/pages/HomePage.js
> +      <div className="hero-section">
Taken care of

2020-12-07 23:34 UTC, PatrickDohn commented on src/components/pages/HomePage.js
> +        <div className="triple-content">
Taken care of

2020-12-07 23:34 UTC, PatrickDohn commented on src/components/pages/HomePage.js
> +        <div className="footer-content">
Taken care of

2020-12-07 23:35 UTC, PatrickDohn commented on src/scss/HomePage.scss
> +  width: 100vw;
Taken care of

2020-12-07 23:49 UTC, davidholyko approved these changes
LGTM

2020-12-07 23:51 UTC, merged